# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dsKLunzMBgehOsZcpGHFSh2Nh7-3P436
"""

# mount drive with colab
from google.colab import drive
drive.mount('/content/drive')

!pwd

# copy the zip file from drive
# Give zip file name according to yours in 5 places # 1
!cp -r drive/'My Drive'/yolo-v2-darknet-master.zip /content/

from google.colab import drive
drive.mount('/content/drive')

# unzip the file
# 2
!unzip yolo-v2-darknet-master.zip

!pwd

# Commented out IPython magic to ensure Python compatibility.
# 3
# %cd yolo-v2-darknet-master

!wget https://pjreddie.com/media/files/darknet19_448.conv.23

!ls
!sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
!sed -i 's/GPU=0/GPU=1/g' Makefile

# Commented out IPython magic to ensure Python compatibility.
# %cd ../

!dpkg --configure -a

!pip install tensorflow-gpu==1.15.0

import tensorflow as tf
device_name = tf.test.gpu_device_name()
print(device_name)

print("'sup!'")

!/usr/local/cuda/bin/nvcc --version

# Commented out IPython magic to ensure Python compatibility.
# 4
# %cd yolo-v2-darknet-master

!pwd

!make

!pwd

# Commented out IPython magic to ensure Python compatibility.
# 5
# %cd yolo-v2-darknet-master

!pwd

!./darknet detector train data/obj.data yolov2-tiny.cfg darknet19_448.conv.23 -dont_show

!cp -r /content/yolo-v2-darknet-master/backup/ /content/drive/'My Drive'/

!mkdir backup

!cp -r /content/drive/'My Drive'/backup/* /content/yolo-v2-darknet-master/backup/